-- Migration: create PR review related tables
-- Requires PostgreSQL with pgcrypto for gen_random_uuid()

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Table for PR review records
CREATE TABLE IF NOT EXISTS pr_review_records (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    repo TEXT NOT NULL,
    pr_number INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    status TEXT NOT NULL, -- e.g., pending, completed, escalated
    summary TEXT,
    total_cost_usd FLOAT,
    total_tokens INT
);

-- Table for individual finding records generated by agents
CREATE TABLE IF NOT EXISTS finding_records (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    review_id UUID NOT NULL REFERENCES pr_review_records(id) ON DELETE CASCADE,
    file_path TEXT NOT NULL,
    line_start INT,
    line_end INT,
    symbol TEXT,
    severity TEXT,
    description TEXT,
    confidence FLOAT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- HITL review queue table
CREATE TABLE IF NOT EXISTS hitl_reviews (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    finding_id UUID NOT NULL REFERENCES finding_records(id) ON DELETE CASCADE,
    assigned_to TEXT,
    status TEXT NOT NULL DEFAULT 'pending', -- pending, approved, rejected
    decision TEXT,
    reviewer_comments TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Optional feedback after HITL decision
CREATE TABLE IF NOT EXISTS hitl_feedback (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    hitl_review_id UUID NOT NULL REFERENCES hitl_reviews(id) ON DELETE CASCADE,
    feedback TEXT,
    rating INT, -- e.g., 1-5
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Indexes for fast lookup
CREATE INDEX IF NOT EXISTS idx_pr_review_repo_pr ON pr_review_records (repo, pr_number);
CREATE INDEX IF NOT EXISTS idx_finding_review_id ON finding_records (review_id);
CREATE INDEX IF NOT EXISTS idx_hitl_status ON hitl_reviews (status);
